plugins.zdf_mediathek Added missing headers for http.get (#653)
* plugins.zdf_mediathek Added missing headers for http.get

    - Removed unused import
    - Removed "match" it was not used
    - Added missing "name" it was not defined
    - Added an **info message** for how to get a **valid link** for tv channels, if someone uses
    `streamlink https://www.zdf.de/live-tv`
    - Fixed 403 Client Error (**Added headers for http.get**)

    ```
    [cli][info] Found matching plugin zdf_mediathek for URL https://www.zdf.de/comedy/heute-show/heute-show-vom-24-februar-2017-100.html
    error: Unable to open URL: https://api.zdf.de/tmd/2/portal/vod/ptmd/mediathek/170224_sendung_hsh (403 Client Error: Forbidden for url: https://api.zdf.de/tmd/2/portal/vod/ptmd/mediathek/170224_sendung_hsh)
    ```

* plugins.zdf_mediathek added an "option" check if there are no options you are likely geo blocked

only HLS streams are geoblocked
`[error] Failed to extract HLS streams:` should be still there but

HDS streams are not geoblocked with a random US Proxy

* plugins.zdf_mediathek geo-restricted informations

Error message will be only spammed in debug mode.

* changed debug back to error