tests: use unittest instead of pytest for itertags error (#1999)
The tests won't pass with `python setup.py test`,
use unittest instead of pytest.

```
======================================================================
FAIL: test_itertags_multi_attrs (tests.test_plugin_utils.TestPluginUtil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_plugin_utils.py", line 59, in 
test_itertags_multi_attrs
    self.assertEqual(metas[0].text, None)
AssertionError: 'Title' != None

======================================================================
FAIL: test_no_end_tag (tests.test_plugin_utils.TestPluginUtil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_plugin_utils.py", line 80, in test_no_end_tag
    self.assertEqual(links[0].text, None)
AssertionError: '' != None

```