utils.parse_xml: allow a tab for ignore_ns
A playlist has tabs instead of spaces,
`self.node` is `{urn:mpeg:dash:schema:mpd:2011}mpd` instead of `mpd`,
because `ignore_ns` did not work.

```
Traceback (most recent call last):
  File "env/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink', 'console_scripts', 'streamlink')()
  File "src/streamlink_cli/main.py", line 1007, in main
    handle_url()
  File "src/streamlink_cli/main.py", line 557, in handle_url
    streams = fetch_streams(plugin)
  File "src/streamlink_cli/main.py", line 437, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "src/streamlink/plugin/plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "src/streamlink/plugins/dash.py", line 59, in _get_streams
    return DASHStream.parse_manifest(self.session, mpdurl)
  File "src/streamlink/stream/dash.py", line 180, in parse_manifest
    mpd = MPD(session.http.xml(res, ignore_ns=True), base_url=urlunparse(urlp), url=url)
  File "src/streamlink/stream/dash_manifest.py", line 229, in __init__
    super(MPD, self).__init__(node, root=self, *args, **kwargs)
  File "src/streamlink/stream/dash_manifest.py", line 151, in __init__
    raise MPDParsingError("root tag did not match the expected tag: {}".format(self.__tag__))
streamlink.stream.dash_manifest.MPDParsingError: root tag did not match the expected tag: MPD
```

---

`DeprecationWarning: Please use assertEqual instead.`

---

Flake8 import errors