plugins.zdf_mediathek Added missing headers for http.get
    - Removed unused import
    - Removed "match" it was not used
    - Added missing "name" it was not defined
    - Added an **info message** for how to get a **valid link** for tv channels, if someone uses
    `streamlink https://www.zdf.de/live-tv`
    - Fixed 403 Client Error (**Added headers for http.get**)

    ```
    [cli][info] Found matching plugin zdf_mediathek for URL https://www.zdf.de/comedy/heute-show/heute-show-vom-24-februar-2017-100.html
    error: Unable to open URL: https://api.zdf.de/tmd/2/portal/vod/ptmd/mediathek/170224_sendung_hsh (403 Client Error: Forbidden for url: https://api.zdf.de/tmd/2/portal/vod/ptmd/mediathek/170224_sendung_hsh)
    ```