stream.hls_playlist: removed int check from PROGRAM-ID (#1707)
* stream.hls_playlist: removed int check from PROGRAM-ID

strings are now valid and won't error

```
error: Failed to parse playlist: invalid literal for int() with base 10: 'be38842539da4fe7ad5265ec9ced7153'
```

example

https://rutube.ru/video/11bbbec75a2ceb8cf446ad16813c6eec/

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=700000, CODECS="avc1.42E01E,mp4a.40.5"
288p.m3u8?i=512x288_700000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=700000, CODECS="avc1.42E01E,mp4a.40.5"
288p.m3u8?i=512x288_700000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=1300000, CODECS="avc1.42c01f,mp4a.40.5"
360p.m3u8?i=640x360_1300000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=1300000, CODECS="avc1.42c01f,mp4a.40.5"
360p.m3u8?i=640x360_1300000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=2000000, CODECS="avc1.4D401F,mp4a.40.5"
576p.m3u8?i=896x504_2000000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=2000000, CODECS="avc1.4D401F,mp4a.40.5"
576p.m3u8?i=896x504_2000000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=3600000, CODECS="avc1.640029,mp4a.40.5"
720p.m3u8?i=1280x720_3600000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=3600000, CODECS="avc1.640029,mp4a.40.5"
720p.m3u8?i=1280x720_3600000
```

* tests.hls_playlist: Fixed tests

it's not important if it's a str or int because streamlink doesn't use
it at the moment